feat: tooltip component
Douro-ui/design-system pull request #118
Opened 2024-09-24 12:14 UTC by Arthurmqz

This update addresses the need for a customizable and reusable set of a tooltip component in the project.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-09-30 16:56 UTC, joaoprcosta commented on packages/components/tooltip/src/hooks/__tests__/useClickOutside.spec.tsx
> +    document.body.removeChild(ref.current);
This action could be set in 'afterAll' function outside each test at the beginning.

```suggestion
    afterAll(() => document.body.removeChild(ref.current);)
```

2024-10-02 09:05 UTC, jessywork requested changes

2024-10-02 09:05 UTC, jessywork commented on packages/components/tooltip/src/Tooltip.tsx
> +          style={{ top: `${coords.top}px`, left: `${coords.left}px` }}
you can pass it to the styles file

2024-10-02 09:05 UTC, jessywork commented on packages/components/tooltip/src/tooltip.styles.ts
> +          bottom: -5px; /* Flecha abaixo do tooltip */
remove comment

2024-10-02 09:05 UTC, jessywork commented on packages/components/tooltip/src/tooltip.styles.ts
> +          top: -5px; /* Flecha acima do tooltip */
remove comment

2024-10-02 09:05 UTC, jessywork commented on packages/components/tooltip/src/tooltip.styles.ts
> +          right: -5px; /* Flecha à esquerda do tooltip */
remove comment

2024-10-02 09:05 UTC, jessywork commented on packages/components/tooltip/src/tooltip.styles.ts
> +          left: -5px; /* Flecha à direita do tooltip */
remove comment

2024-10-03 08:57 UTC, jessywork approved these changes

2024-10-07 09:31 UTC, JuniorDiasOliveira approved these changes

2024-10-08 16:16 UTC, merged