Refactor/checkbox component
Douro-ui/design-system pull request #153
Opened 2024-11-19 14:57 UTC by vzdiogo

This update addresses the need for a customizable and reusable set of Checkbox component in the project.

## Type of change

- [ ] Other: Style according to the new design, component architecture update.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-11-20 09:24 UTC, jessywork commented
![image](https://github.com/user-attachments/assets/fcba641d-1584-49d7-a871-7b54509e0741)
you need to fix this

2024-11-20 09:27 UTC, jessywork commented
![image](https://github.com/user-attachments/assets/76e4201a-6022-4b4f-94fb-af7868904eba)
missing indeterminate style

2024-11-20 09:28 UTC, jessywork commented
missing controls on storybook

2024-11-20 09:30 UTC, jessywork commented
missing the size of the checkboxes

2024-11-20 09:31 UTC, jessywork commented
![image](https://github.com/user-attachments/assets/b08d7ada-8cd6-4b86-b11d-b6f08173590b)
missing group style

2024-11-20 09:38 UTC, jessywork requested changes

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/__tests__/Checkbox.spec.tsx
> +  it.only('renders correctly with label', () => {
remove only

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  checkedBeforeBorderColor?: string;
checkedBeforeBorderColor is not being used

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  disabledborderColor?: string;
CamelCase

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  hovercheckedBorderColor?: string;
CamelCase

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  hovercheckedBackgroundColor?: string;
CamelCase

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  activecheckedBorderColor?: string;
CamelCase

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  activeBeforecheckedBackgroundColor?: string;
CamelCase

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  disablecheckedBorderColor?: string;
CamelCase

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  disabledBeforecheckedBackgroundColor?: string;
CamelCase

2024-11-20 09:38 UTC, jessywork commented on packages/components/checkbox/src/checkbox.types.ts
> +  disabledBeforecheckedBorderColor?: string;
CamelCase

2024-11-20 11:01 UTC, JuniorDiasOliveira commented on packages/components/checkbox/src/checkbox.styles.ts
> +      return 'font-size: 1rem;';
Switch case is forbidden, try to come up with a different solution

2025-02-25 11:17 UTC, jessywork commented
The title of each group size is incorrect

2025-02-25 11:17 UTC, jessywork commented
The box size is also incorrect

2025-02-25 11:20 UTC, jessywork commented
The message error is not centralized and the font size is not correct

2025-02-25 11:31 UTC, jessywork commented on packages/components/checkbox/src/CheckboxGroup.stories.tsx
> +    error: '',
i think error should be an boolean, it does not make sense be an empty string

2025-08-19 14:12 UTC, closed without merging