feat: picture component
Douro-ui/design-system pull request #79
Opened 2024-07-31 12:53 UTC by jessywork

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-07-31 17:20 UTC, JuniorDiasOliveira requested changes

2024-07-31 17:20 UTC, JuniorDiasOliveira commented on packages/components/picture/src/__tests__/Picture.spec.tsx
> +  it.only('applies custom styles', () => {
remove the .only

2024-07-31 17:21 UTC, JuniorDiasOliveira commented
Include a proper description for this PR on the PR description

2024-08-09 09:02 UTC, vzdiogo approved these changes

2024-08-09 09:05 UTC, Arthurmqz approved these changes

2024-08-09 11:12 UTC, JuniorDiasOliveira approved these changes

2024-08-09 11:17 UTC, merged